'use client';

import { Eye, Download } from 'lucide-react';
import { Badge } from '@/components/ui/badge';

export default function ReportsTable() {
  const reports = [
    { id: 1, name: 'Monthly Indian Payroll Summary', category: 'Payroll (INR)', generatedBy: 'Admin IT', date: '23 Aug 2026', format: 'PDF' },
    { id: 2, name: 'Attendance & GPS Punch Logs', category: 'Attendance', generatedBy: 'HR Manager', date: '22 Aug 2026', format: 'Excel' },
    { id: 3, name: 'Casual & Privilege Leave Balance Report', category: 'Leave', generatedBy: 'Admin IT', date: '20 Aug 2026', format: 'PDF' },
    { id: 4, name: 'Employee Performance Appraisal', category: 'Performance', generatedBy: 'HR Manager', date: '18 Aug 2026', format: 'Excel' },
    { id: 5, name: 'Salary Register & TDS Deductions', category: 'Payroll (INR)', generatedBy: 'Accounts Officer', date: '15 Aug 2026', format: 'CSV' },
  ];

  const handleView = (name: string) => {
    alert(`Viewing ${name}`);
  };

  const handleDownload = (name: string) => {
    alert(`Downloading ${name}`);
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h2 className="text-xs font-bold uppercase tracking-wider text-zinc-900 dark:text-zinc-100">
          Generated Master Reports & Audit Files
        </h2>
        <Badge variant="brand">{reports.length} Reports Ready</Badge>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-left font-medium">
          <thead className="bg-zinc-50 dark:bg-zinc-900/80 border-b border-zinc-200 dark:border-zinc-800">
            <tr>
              <th className="py-3 px-4 text-xs font-medium text-zinc-500 uppercase">Report Title</th>
              <th className="py-3 px-4 text-xs font-medium text-zinc-500 uppercase">Category</th>
              <th className="py-3 px-4 text-xs font-medium text-zinc-500 uppercase">Generated By</th>
              <th className="py-3 px-4 text-xs font-medium text-zinc-500 uppercase">Generated Date</th>
              <th className="py-3 px-4 text-xs font-medium text-zinc-500 uppercase">File Format</th>
              <th className="py-3 px-4 text-xs font-medium text-zinc-500 uppercase text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-zinc-200 dark:divide-zinc-800">
            {reports.map((report) => (
              <tr key={report.id} className="hover:bg-zinc-50/60 dark:hover:bg-zinc-950/40 transition-colors">
                <td className="py-3.5 px-4 text-xs font-semibold text-zinc-900 dark:text-zinc-50">
                  {report.name}
                </td>
                <td className="py-3.5 px-4">
                  <Badge variant="secondary" className="text-[10px]">
                    {report.category}
                  </Badge>
                </td>
                <td className="py-3.5 px-4 text-xs text-zinc-700 dark:text-zinc-300">
                  {report.generatedBy}
                </td>
                <td className="py-3.5 px-4 text-xs text-zinc-500 whitespace-nowrap">
                  {report.date}
                </td>
                <td className="py-3.5 px-4">
                  <Badge variant="outline" className="text-[10px] font-mono uppercase">
                    {report.format}
                  </Badge>
                </td>
                <td className="py-3.5 px-4 text-right whitespace-nowrap">
                  <div className="flex items-center justify-end gap-1.5">
                    <button
                      onClick={() => handleView(report.name)}
                      className="h-8 w-8 rounded-full bg-blue-500/10 text-blue-600 hover:bg-blue-500 hover:text-white flex items-center justify-center transition-colors"
                      title="View Report"
                    >
                      <Eye className="h-3.5 w-3.5" />
                    </button>
                    <button
                      onClick={() => handleDownload(report.name)}
                      className="h-8 w-8 rounded-full bg-[#94cb3d]/15 text-[#94cb3d] hover:bg-[#94cb3d] hover:text-white flex items-center justify-center transition-colors"
                      title="Download Report"
                    >
                      <Download className="h-3.5 w-3.5" />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
